import jsPDF from 'jspdf'

/**
 * Generate and download a PDF report of an interaction summary
 * @param {string} summary - The interaction summary text
 * @param {Object} interaction - The interaction data
 */
export const exportSummaryToPDF = (summary, interaction) => {
  try {
    // Create new PDF document
    const pdf = new jsPDF()
    
    // Set document properties
    pdf.setProperties({
      title: 'Police Interaction Summary',
      subject: 'Legal Documentation',
      author: 'Pocket Advocate',
      creator: 'Pocket Advocate App'
    })

    // Add header
    pdf.setFontSize(20)
    pdf.setFont('helvetica', 'bold')
    pdf.text('POLICE INTERACTION SUMMARY', 20, 30)
    
    // Add timestamp
    pdf.setFontSize(10)
    pdf.setFont('helvetica', 'normal')
    pdf.text(`Generated: ${new Date().toLocaleString()}`, 20, 40)
    
    // Add horizontal line
    pdf.line(20, 45, 190, 45)
    
    // Process summary text
    const lines = summary.split('\n')
    let yPosition = 55
    const pageHeight = pdf.internal.pageSize.height
    const margin = 20
    const lineHeight = 6
    
    pdf.setFontSize(11)
    
    lines.forEach((line) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 30) {
        pdf.addPage()
        yPosition = 30
      }
      
      // Handle different line types
      if (line.trim() === '') {
        yPosition += lineHeight / 2
        return
      }
      
      // Headers (all caps lines)
      if (line === line.toUpperCase() && line.trim().length > 0 && !line.includes(':')) {
        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(12)
        yPosition += lineHeight
      } else if (line.includes(':') && line.split(':')[1].trim() !== '') {
        // Key-value pairs
        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(10)
      } else {
        // Regular text
        pdf.setFont('helvetica', 'normal')
        pdf.setFontSize(10)
      }
      
      // Split long lines
      const splitText = pdf.splitTextToSize(line, 170)
      splitText.forEach((textLine) => {
        if (yPosition > pageHeight - 30) {
          pdf.addPage()
          yPosition = 30
        }
        pdf.text(textLine, margin, yPosition)
        yPosition += lineHeight
      })
    })
    
    // Add footer with disclaimer
    const totalPages = pdf.internal.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setFont('helvetica', 'italic')
      pdf.text(
        'This document was generated by Pocket Advocate and is for documentation purposes only.',
        margin,
        pageHeight - 20
      )
      pdf.text(
        `Page ${i} of ${totalPages}`,
        190 - margin,
        pageHeight - 20,
        { align: 'right' }
      )
    }
    
    // Generate filename
    const date = new Date(interaction.timestamp).toISOString().split('T')[0]
    const filename = `police-interaction-${date}-${Date.now()}.pdf`
    
    // Save the PDF
    pdf.save(filename)
    
    return true
  } catch (error) {
    console.error('Failed to generate PDF:', error)
    throw new Error('Failed to generate PDF report')
  }
}

/**
 * Generate a quick reference card PDF with rights information
 * @param {Object} rightsInfo - Rights information for the user's state
 * @param {string} state - User's state
 */
export const exportRightsCardToPDF = (rightsInfo, state) => {
  try {
    const pdf = new jsPDF()
    
    // Set document properties
    pdf.setProperties({
      title: 'Know Your Rights - Quick Reference',
      subject: 'Legal Rights Information',
      author: 'Pocket Advocate',
      creator: 'Pocket Advocate App'
    })

    // Header
    pdf.setFontSize(18)
    pdf.setFont('helvetica', 'bold')
    pdf.text('KNOW YOUR RIGHTS', 20, 30)
    pdf.text('Quick Reference Card', 20, 40)
    
    // State info
    pdf.setFontSize(12)
    pdf.text(`State: ${state || 'General'}`, 20, 55)
    
    // Add line
    pdf.line(20, 60, 190, 60)
    
    let yPos = 75
    
    // Rights section
    if (rightsInfo?.rights) {
      pdf.setFontSize(14)
      pdf.setFont('helvetica', 'bold')
      pdf.text('YOUR RIGHTS:', 20, yPos)
      yPos += 10
      
      pdf.setFontSize(11)
      pdf.setFont('helvetica', 'normal')
      rightsInfo.rights.forEach((right, index) => {
        const text = `${index + 1}. ${right}`
        const splitText = pdf.splitTextToSize(text, 170)
        splitText.forEach((line) => {
          pdf.text(line, 25, yPos)
          yPos += 6
        })
        yPos += 2
      })
    }
    
    yPos += 10
    
    // Warnings section
    if (rightsInfo?.warnings) {
      pdf.setFontSize(14)
      pdf.setFont('helvetica', 'bold')
      pdf.text('IMPORTANT WARNINGS:', 20, yPos)
      yPos += 10
      
      pdf.setFontSize(11)
      pdf.setFont('helvetica', 'normal')
      rightsInfo.warnings.forEach((warning, index) => {
        const text = `• ${warning}`
        const splitText = pdf.splitTextToSize(text, 170)
        splitText.forEach((line) => {
          pdf.text(line, 25, yPos)
          yPos += 6
        })
        yPos += 2
      })
    }
    
    // Footer
    pdf.setFontSize(8)
    pdf.setFont('helvetica', 'italic')
    pdf.text(
      'Generated by Pocket Advocate - This is not legal advice. Consult an attorney for legal guidance.',
      20,
      280
    )
    
    // Save
    const filename = `rights-reference-${state || 'general'}-${Date.now()}.pdf`
    pdf.save(filename)
    
    return true
  } catch (error) {
    console.error('Failed to generate rights card PDF:', error)
    throw new Error('Failed to generate rights reference card')
  }
}

/**
 * Create a printable legal scripts card
 * @param {Object} scripts - Legal scripts by language and scenario
 * @param {string} language - Selected language
 */
export const exportScriptCardToPDF = (scripts, language = 'english') => {
  try {
    const pdf = new jsPDF()
    
    pdf.setProperties({
      title: 'Legal Scripts - Quick Reference',
      subject: 'Legal Response Scripts',
      author: 'Pocket Advocate',
      creator: 'Pocket Advocate App'
    })

    // Header
    pdf.setFontSize(18)
    pdf.setFont('helvetica', 'bold')
    pdf.text('LEGAL RESPONSE SCRIPTS', 20, 30)
    
    pdf.setFontSize(12)
    pdf.text(`Language: ${language === 'spanish' ? 'Español' : 'English'}`, 20, 45)
    
    pdf.line(20, 50, 190, 50)
    
    let yPos = 65
    const pageHeight = pdf.internal.pageSize.height
    
    // Add scripts
    Object.entries(scripts).forEach(([scenario, scriptData]) => {
      // Check for new page
      if (yPos > pageHeight - 60) {
        pdf.addPage()
        yPos = 30
      }
      
      // Scenario title
      pdf.setFontSize(14)
      pdf.setFont('helvetica', 'bold')
      pdf.text(scriptData.title.toUpperCase(), 20, yPos)
      yPos += 10
      
      // Script text
      pdf.setFontSize(11)
      pdf.setFont('helvetica', 'normal')
      const scriptLines = pdf.splitTextToSize(scriptData.script, 170)
      scriptLines.forEach((line) => {
        if (yPos > pageHeight - 30) {
          pdf.addPage()
          yPos = 30
        }
        pdf.text(line, 25, yPos)
        yPos += 6
      })
      
      yPos += 15
    })
    
    // Footer
    pdf.setFontSize(8)
    pdf.setFont('helvetica', 'italic')
    pdf.text(
      'Practice these scripts beforehand. Stay calm and respectful during interactions.',
      20,
      pageHeight - 20
    )
    
    const filename = `legal-scripts-${language}-${Date.now()}.pdf`
    pdf.save(filename)
    
    return true
  } catch (error) {
    console.error('Failed to generate scripts PDF:', error)
    throw new Error('Failed to generate scripts reference card')
  }
}
