import React, { createContext, useState, useEffect } from 'react'

export const InteractionContext = createContext()

export const InteractionProvider = ({ children }) => {
  const [interactions, setInteractions] = useState([])

  // Load interactions from localStorage on mount
  useEffect(() => {
    const savedInteractions = localStorage.getItem('pocket-advocate-interactions')
    if (savedInteractions) {
      try {
        setInteractions(JSON.parse(savedInteractions))
      } catch (error) {
        console.error('Failed to load interactions:', error)
      }
    }
  }, [])

  // Save interactions to localStorage whenever they change
  useEffect(() => {
    localStorage.setItem('pocket-advocate-interactions', JSON.stringify(interactions))
  }, [interactions])

  const saveInteraction = async (interaction) => {
    setInteractions(prev => [interaction, ...prev])
  }

  const generateSummary = async (interaction) => {
    // Simulate AI summary generation
    // In a real app, this would call OpenAI API
    await new Promise(resolve => setTimeout(resolve, 2000))

    const summary = `POLICE INTERACTION SUMMARY

Date & Time: ${new Date(interaction.timestamp).toLocaleString()}
Location: ${interaction.location.state || 'Unknown State'}${interaction.location.coordinates ? ` (${interaction.location.coordinates.latitude.toFixed(4)}, ${interaction.location.coordinates.longitude.toFixed(4)})` : ''}
Type: ${interaction.type.replace('-', ' ').toUpperCase()}

OFFICER INFORMATION:
${interaction.officerBadge ? `Badge Number: ${interaction.officerBadge}` : 'Badge Number: Not provided'}
${interaction.officerName ? `Name: ${interaction.officerName}` : 'Name: Not provided'}
${interaction.vehicleInfo ? `Vehicle/Unit: ${interaction.vehicleInfo}` : 'Vehicle/Unit: Not provided'}

INCIDENT DESCRIPTION:
${interaction.description || 'No description provided'}

WITNESSES:
${interaction.witnesses || 'None reported'}

OUTCOME:
${interaction.outcome || 'Not specified'}

ADDITIONAL NOTES:
- This summary was generated automatically
- Keep this record for your files
- Contact legal counsel if you have concerns about this interaction
- Your rights were: [Right to remain silent, Right to refuse consent to search, Right to ask if you're free to go]

Generated by Pocket Advocate on ${new Date().toLocaleString()}`

    return summary
  }

  const value = {
    interactions,
    saveInteraction,
    generateSummary
  }

  return (
    <InteractionContext.Provider value={value}>
      {children}
    </InteractionContext.Provider>
  )
}